testexport.bbclass: capture meta/lib/oe
oeqa runtime tests like stap.py depend oe library so capture
it to testexport tar ball so that test environments can run the
test too. Fixes:

2026-08-13 06:44:37,419 - runtime - INFO - ERROR: test_stap (stap.StapTest.test_stap)
2026-08-13 06:44:37,420 - runtime - INFO - ----------------------------------------------------------------------
2026-08-13 06:44:37,420 - runtime - INFO - Traceback (most recent call last):
  File "/lava-downloads/core-image-sato-sdk/meta/lib/oeqa/core/decorator/__init__.py", line 35, in wrapped_f
    return func(*args, **kwargs)
  File "/lava-downloads/core-image-sato-sdk/meta/lib/oeqa/core/decorator/__init__.py", line 35, in wrapped_f
    return func(*args, **kwargs)
  File "/lava-downloads/core-image-sato-sdk/meta/lib/oeqa/core/decorator/__init__.py", line 35, in wrapped_f
    return func(*args, **kwargs)
  [Previous line repeated 1 more time]
  File "/lava-downloads/core-image-sato-sdk/meta/lib/oeqa/runtime/cases/stap.py", line 19, in test_stap
    from oe.utils import parallel_make_value
ModuleNotFoundError: No module named 'oe'

Signed-off-by: Mikko Rapeli <mikko.rapeli@linaro.org>
Signed-off-by: Mathieu Dubois-Briand <mathieu.dubois-briand@bootlin.com>